export default defineAppConfig({
  ui: {
    colors: {
      primary: "danube",
      secondary: "pumpkin",
      neutral: "stone",
      // Custom colors for products
      copilot: "orchid",
      seoAudit: "lima",
    },
    icons: {
      caution: "i-ri-alert-line",
      copy: "i-ri-file-copy-line",
      copyCheck: "i-ri-checkbox-circle-line",
      dark: "i-ri-moon-fill",
      error: "i-ri-close-circle-line",
      external: "i-ri-external-link-line",
      eye: "i-ri-eye-off",
      eyeOff: "i-ri-eye-off-line",
      file: "i-ri-file-text-line",
      folder: "i-ri-folder-line",
      folderOpen: "i-ri-folder-open-line",
      hash: "i-ri-hashtag",
      info: "i-ri-information-line",
      light: "i-ri-sun-fill",
      menu: "i-ri-menu-line",
      panelClose: "i-ri-expand-left-line",
      panelOpen: "i-ri-expand-right-line",
      success: "i-lucide-circle-check",
      system: "i-ri-computer-line",
      tip: "i-ri-lightbulb-line",
      warning: "i-ri-alert-line",
      arrowLeft: "i-ri-arrow-left-line",
      arrowRight: "i-ri-arrow-right-line",
      check: "i-ri-check-line",
      chevronDoubleLeft: "i-ri-arrow-left-double-line",
      chevronDoubleRight: "i-ri-arrow-right-double-line",
      chevronDown: "i-ri-arrow-down-s-line",
      chevronLeft: "i-ri-arrow-left-s-line",
      chevronRight: "i-ri-arrow-right-s-line",
      chevronUp: "i-ri-arrow-up-s-line",
      close: "i-ri-close-line",
      ellipsis: "i-ri-more-fill",
      loading: "i-ri-refresh-line",
      minus: "i-ri-subtract-line",
      plus: "i-ri-add-line",
      search: "i-ri-search-line",
    },
  },
});
