<template>
  <PanelMock>
    <PanelDialog
      size="medium"
      :fields="TRANSLATOR_DIALOG_FIELDS"
      :value="TRANSLATOR_DIALOG_VALUE"
      :buttons="TRANSLATOR_DIALOG_BUTTONS"
    />
  </PanelMock>
</template>
