<template>
  <PanelMock>
    <PanelDialog
      size="medium"
      :fields="TRANSLATOR_DIALOG_FIELDS"
      :value="TRANSLATOR_DIALOG_VALUE"
      cancel-button
      :submit-button="TRANSLATOR_DIALOG_SUBMIT_BUTTON"
    />
  </PanelMock>
</template>
